# Generated by Django 4.2.3 on 2023-08-04 08:49

import basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('profile_url', models.ImageField(null=True, upload_to=basic.models.profile_upload_to)),
                ('image_url', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(null=True, upload_to=basic.models.scan_upload_to)),
            ],
        ),
    ]
