# Generated by Django 4.2.3 on 2023-07-31 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='creator',
        ),
    ]
