# Generated by Django 4.2.3 on 2023-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_print_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='q',
            field=models.TextField(default=0),
        ),
    ]
