# Generated by Django 4.2.3 on 2023-07-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_print_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print',
            old_name='q',
            new_name='image_url',
        ),
    ]
