# Generated by Django 4.2.3 on 2023-07-31 20:17

import basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_alter_print_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='image_url',
            field=models.ImageField(null=True, upload_to=basic.models.upload_to),
        ),
    ]
